"""
Action model representing remediation actions for incidents.

Senior Engineering Note:
- State machine pattern for action lifecycle
- Approval workflow tracking
- Execution result auditing
"""
import enum
from datetime import datetime
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import JSON, Enum as SQLEnum, ForeignKey, Index, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.incident import Incident


class ActionType(str, enum.Enum):
    """Types of remediation actions."""

    RESTART_POD = "restart_pod"
    SCALE_UP = "scale_up"
    SCALE_DOWN = "scale_down"
    ROLLBACK_DEPLOYMENT = "rollback_deployment"
    TOGGLE_FEATURE_FLAG = "toggle_feature_flag"
    CLEAR_CACHE = "clear_cache"
    DRAIN_NODE = "drain_node"
    CUSTOM = "custom"


class ActionStatus(str, enum.Enum):
    """Action lifecycle states."""

    PROPOSED = "proposed"  # Generated by system
    PENDING_APPROVAL = "pending_approval"  # Awaiting human review
    APPROVED = "approved"  # Approved by human
    REJECTED = "rejected"  # Rejected by human
    EXECUTING = "executing"  # Currently executing
    SUCCEEDED = "succeeded"  # Successfully executed
    FAILED = "failed"  # Execution failed
    ROLLED_BACK = "rolled_back"  # Action was rolled back


class RiskLevel(str, enum.Enum):
    """Risk assessment for actions."""

    LOW = "low"  # Safe, reversible actions
    MEDIUM = "medium"  # Some risk, requires approval
    HIGH = "high"  # Risky, requires senior approval
    CRITICAL = "critical"  # Very risky, requires multi-level approval


class Action(Base, TimestampMixin):
    """
    Remediation action proposed or executed for an incident.

    Tracks the full lifecycle from proposal through execution,
    including approval workflow and execution results.
    """

    __tablename__ = "actions"

    # Primary key
    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)

    # Foreign keys
    incident_id: Mapped[UUID] = mapped_column(
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Action details
    action_type: Mapped[ActionType] = mapped_column(
        SQLEnum(ActionType),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    # Target
    target_service: Mapped[str] = mapped_column(String(255), nullable=False)
    target_resource: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="Specific resource ID (pod name, node ID, etc.)",
    )

    # Risk assessment
    risk_level: Mapped[RiskLevel] = mapped_column(
        SQLEnum(RiskLevel),
        nullable=False,
        index=True,
    )
    risk_score: Mapped[float] = mapped_column(
        Numeric(precision=4, scale=3),
        nullable=False,
        comment="Risk score from 0.000 to 1.000",
    )
    blast_radius: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Estimated impact: low, medium, high, critical",
    )

    # Workflow
    status: Mapped[ActionStatus] = mapped_column(
        SQLEnum(ActionStatus),
        nullable=False,
        default=ActionStatus.PROPOSED,
        index=True,
    )

    # Approval tracking
    requires_approval: Mapped[bool] = mapped_column(nullable=False, default=True)
    approved_by: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="User who approved (email or ID)",
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)
    rejection_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Execution
    execution_mode: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="dry_run",
        comment="dry_run or live",
    )
    executed_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)
    execution_duration_seconds: Mapped[Optional[int]] = mapped_column(nullable=True)
    execution_result: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        comment="Detailed execution results or error information",
    )

    # Action parameters
    parameters: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Action-specific parameters",
    )

    # Rollback
    rollback_action_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("actions.id"),
        nullable=True,
        comment="ID of the action that rolled back this action",
    )

    # Relationships
    incident: Mapped["Incident"] = relationship("Incident", back_populates="actions")

    # Indexes
    __table_args__ = (
        Index("idx_action_incident_status", "incident_id", "status"),
        Index("idx_action_incident_status_created", "incident_id", "status", "created_at"),
        Index("idx_action_type_status", "action_type", "status"),
        Index("idx_action_risk_level", "risk_level"),
    )

    def __repr__(self) -> str:
        return (
            f"<Action(id={self.id}, "
            f"type={self.action_type.value}, "
            f"status={self.status.value}, "
            f"risk={self.risk_level.value})>"
        )

    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": str(self.id),
            "incident_id": str(self.incident_id),
            "action_type": self.action_type.value,
            "name": self.name,
            "description": self.description,
            "target_service": self.target_service,
            "target_resource": self.target_resource,
            "risk_level": self.risk_level.value,
            "risk_score": float(self.risk_score),
            "blast_radius": self.blast_radius,
            "status": self.status.value,
            "requires_approval": self.requires_approval,
            "approved_by": self.approved_by,
            "approved_at": self.approved_at.isoformat() if self.approved_at else None,
            "execution_mode": self.execution_mode,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
            "parameters": self.parameters,
            "created_at": self.created_at.isoformat(),
        }
