"""
Hypothesis model representing LLM-generated root cause theories.

Senior Engineering Note:
- Tracks LLM reasoning with full provenance
- Evidence stored as structured JSON
- Confidence score for ranking and decision-making
"""
from typing import TYPE_CHECKING, Optional
from uuid import UUID, uuid4

from sqlalchemy import JSON, ForeignKey, Index, Numeric, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.incident import Incident


class Hypothesis(Base, TimestampMixin):
    """
    LLM-generated hypothesis for incident root cause.

    Each hypothesis represents a potential explanation for an incident,
    generated by the reasoning module with supporting evidence and confidence.
    """

    __tablename__ = "hypotheses"

    # Primary key
    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)

    # Foreign keys
    incident_id: Mapped[UUID] = mapped_column(
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Hypothesis content
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Natural language description of the hypothesis",
    )
    category: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        comment="Category: memory_leak, cpu_spike, network_issue, etc.",
    )

    # Confidence and ranking
    confidence_score: Mapped[float] = mapped_column(
        Numeric(precision=4, scale=3),
        nullable=False,
        index=True,
        comment="Confidence score from 0.000 to 1.000",
    )
    rank: Mapped[int] = mapped_column(
        nullable=False,
        comment="Rank among all hypotheses for this incident (1 = most likely)",
    )

    # Evidence
    evidence: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Structured evidence supporting this hypothesis",
    )
    supporting_signals: Mapped[list[str]] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        comment="List of signal IDs that support this hypothesis",
    )

    # LLM metadata
    llm_model: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="LLM model used for generation",
    )
    llm_prompt_tokens: Mapped[Optional[int]] = mapped_column(nullable=True)
    llm_completion_tokens: Mapped[Optional[int]] = mapped_column(nullable=True)
    llm_reasoning: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="LLM's chain-of-thought reasoning (if available)",
    )

    # Validation
    validated: Mapped[bool] = mapped_column(
        nullable=False,
        default=False,
        comment="Whether this hypothesis was confirmed correct",
    )
    validation_feedback: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Human feedback on hypothesis accuracy",
    )

    # Relationships
    incident: Mapped["Incident"] = relationship("Incident", back_populates="hypotheses")

    # Indexes
    __table_args__ = (
        Index("idx_hypothesis_incident_confidence", "incident_id", "confidence_score"),
        Index("idx_hypothesis_category", "category"),
    )

    def __repr__(self) -> str:
        return (
            f"<Hypothesis(id={self.id}, "
            f"incident_id={self.incident_id}, "
            f"confidence={self.confidence_score:.3f}, "
            f"rank={self.rank})>"
        )

    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": str(self.id),
            "incident_id": str(self.incident_id),
            "description": self.description,
            "category": self.category,
            "confidence_score": float(self.confidence_score),
            "rank": self.rank,
            "evidence": self.evidence,
            "supporting_signals": self.supporting_signals,
            "llm_model": self.llm_model,
            "validated": self.validated,
            "created_at": self.created_at.isoformat(),
        }
