apiVersion: v1
kind: Service
metadata:
  name: airra-backend
  namespace: airra
  labels:
    app: airra-backend
spec:
  selector:
    app: airra-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
